[package]
name = "parquet2"
version = "0.5.1"
license = "Apache-2.0"
description = "Safe implementation of parquet IO."
authors = ["Jorge C. Leitao <jorgecarleitao@gmail.com", "Apache Arrow <dev@arrow.apache.org>"]
readme = "README.md"
edition = "2018"

[lib]
name = "parquet2"
bench = false

[dependencies]
parquet-format-async-temp = "0.2.0"
bitpacking = { version = "0.8.2", features = ["bitpacker1x"] }
streaming-iterator = "0.1.5"

async-stream = { version = "0.3.2", optional = true }
futures = { version = "0.3", optional = true }

snap = { version = "^1.0", optional = true }
brotli = { version = "^3.3", optional = true }
flate2 = { version = "^1.0", optional = true }
lz4 = { version = "^1.23", optional = true }
zstd = { version = "^0.9", optional = true }

[features]
default = ["snappy", "gzip", "lz4", "zstd", "brotli", "stream"]
snappy = ["snap"]
gzip = ["flate2"]
stream = ["futures", "async-stream"]
