[package]
name = "parquet2"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Jorge C. Leitao <jorgecarleitao@gmail.com", "Apache Arrow <dev@arrow.apache.org>"]
readme = "README.md"
edition = "2018"

[dependencies]
parquet-format = "~2.6.1"
thrift = "0.13"
bitpacking = { version = "0.8.2", features = ["bitpacker1x"] }

snap = { version = "1.0", optional = true }
brotli = { version = "3.3", optional = true }
flate2 = { version = "1.0", optional = true }
lz4 = { version = "1.23", optional = true }
zstd = { version = "0.6", optional = true }

[features]
default = ["snappy", "gzip", "lz4", "zstd", "brotli"]
snappy = ["snap"]
gzip = ["flate2"]
